import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/Link';
import styles from '../styles/Home.module.css'




export default function Home({list}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Sobre o sistema
        </h1>

        

        Este é um sistema desenvolvido/copiado em uma noite. Com mais tempo e dedicação pode ser aprimorado

       



      </main>

    </div>
  )
}


export async function getServerSideProps(){
  const res= await fetch('http://codigo01-k6f27dpo0-equipe-1.vercel.app/api/trending');
  const json= await res.json();
  return {
    props:{
      list: json.list
    }


  };

}